# Generated by Django 2.2.11 on 2020-03-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regionalcase',
            old_name='name',
            new_name='region',
        ),
    ]
