# Generated by Django 2.2.11 on 2020-03-17 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0002_auto_20200317_0251'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_id', models.IntegerField(blank=True)),
                ('name', models.CharField(max_length=300)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('province', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('contact', models.CharField(max_length=300)),
                ('hospital_type', models.CharField(max_length=200)),
                ('service_level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')])),
                ('capacity', models.IntegerField()),
                ('covid_capacity', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('notes', models.TextField(max_length=300)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.RegionalCase')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('case_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.IntegerField()),
                ('nationality', models.CharField(max_length=100)),
                ('overseas_travel', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('country_visited_0', models.CharField(blank=True, max_length=40)),
                ('country_visited_1', models.CharField(blank=True, max_length=40)),
                ('country_visited_2', models.CharField(blank=True, max_length=40)),
                ('exposure', models.CharField(max_length=100)),
                ('exposure_link', models.CharField(max_length=300)),
                ('onset_date', models.DateField()),
                ('admission_date', models.DateField()),
                ('lab_confirmation_date', models.DateField()),
                ('residence_city_mun', models.CharField(max_length=100)),
                ('city_mun_psgc', models.CharField(max_length=50)),
                ('residence_prov', models.CharField(max_length=100)),
                ('prov_psgc', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, choices=[('recovered', 'Recovered'), ('admitted', 'Admitted'), ('dead', 'Dead')], max_length=20)),
                ('death_date', models.DateField(blank=True)),
                ('death_cause', models.CharField(blank=True, max_length=300)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('admitted_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.HealthFacility')),
                ('symptoms', models.ManyToManyField(to='patients.Symptom')),
            ],
        ),
    ]
