# Generated by Django 2.2.11 on 2020-03-17 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20200317_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='admitted_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.HealthFacility'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='city_mun_psgc',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prov_psgc',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='residence_city_mun',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='residence_prov',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
