# Generated by Django 2.2.11 on 2020-03-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20200317_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthfacility',
            name='notes',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='patient',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
