# Generated by Django 2.2.11 on 2020-03-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20200317_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='exposure_link',
        ),
        migrations.AddField(
            model_name='patient',
            name='exposure_link',
            field=models.ManyToManyField(blank=True, null=True, related_name='_patient_exposure_link_+', to='patients.Patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='symptoms',
            field=models.ManyToManyField(blank=True, null=True, to='patients.Symptom'),
        ),
    ]
