# Generated by Django 3.0.4 on 2020-03-18 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20200317_2203'),
        ('patients', '0004_auto_20200317_0954'),
    ]

    operations = [
    ]
