# Generated by Django 2.2.11 on 2020-03-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20200318_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthfacility',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='exposure_link',
            field=models.ManyToManyField(blank=True, related_name='_patient_exposure_link_+', to='patients.Patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='symptoms',
            field=models.ManyToManyField(blank=True, to='patients.Symptom'),
        ),
    ]
