# Generated by Django 3.0.4 on 2020-03-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_merge_20200318_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthfacility',
            name='covid_capacity',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='region',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='service_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
