# Generated by Django 3.0.4 on 2020-03-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_auto_20200318_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthfacility',
            name='service_level',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
