# Generated by Django 3.0.4 on 2020-03-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_auto_20200318_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthfacility',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
