# Generated by Django 3.0.4 on 2020-03-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_auto_20200318_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthfacility',
            name='hospital_id',
            field=models.IntegerField(null=True),
        ),
    ]
