# Generated by Django 3.0.4 on 2020-03-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_auto_20200318_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthfacility',
            name='capacity',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
